# Generated by Django 2.2.8 on 2020-12-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('uname', models.CharField(max_length=30)),
                ('ulocation', models.CharField(max_length=30)),
            ],
        ),
    ]
